'use client';

// Generated by the Shaders editor. A bare Shaders component: mount it inside a
// ShaderScene. Fields are functions of the sample position — warping is
// calling a field at a shifted point — and every editor dial arrived below
// as a prop with the editor's value as its default.
import { useEffect } from 'react';

import { colorRamp, displace, simplexNoise } from '@camp-dev/shaders';
import {
  useAnimatableSpeed,
  useAnimatableUniform,
  useShaderContext,
} from '@camp-dev/shaders-react';
import { parseColorString } from '@camp-dev/shaders/color';
import {
  clamp,
  cos,
  dot,
  fract,
  mix,
  sin,
  smoothstep,
  sub,
  uniform,
  uv,
  vec2,
  vec3,
} from 'three/tsl';
import type { ShaderNodeObject } from 'three/tsl';
import { Mesh, MeshBasicNodeMaterial, PlaneGeometry } from 'three/webgpu';
import type { Node } from 'three/webgpu';

type TSLNode = ShaderNodeObject<Node>;

export interface GeneratedShaderProps {
  /** Gradient angle, 0 to 360. Defaults to 45. */
  gradientAngle?: number;
  /** Gradient repeat, 1 to 10. Defaults to 1. */
  gradientRepeat?: number;
  /** Gradient speed, 0 to 1. Defaults to 0. */
  gradientSpeed?: number;
  /** Noise scale, 0.5 to 10. Defaults to 3. */
  noiseScale?: number;
  /** Noise contrast, 0 to 4. Defaults to 1. */
  noiseContrast?: number;
  /** Noise balance, 0 to 1. Defaults to 0.5. */
  noiseBalance?: number;
  /** Noise speed, 0 to 1. Defaults to 0.15. */
  noiseSpeed?: number;
  /** Warp amount, 0 to 1. Defaults to 0.35. */
  warpAmount?: number;
  /** Blend amount, 0 to 1. Defaults to 0.5. */
  blendAmount?: number;
}

export function GeneratedShader({
  gradientAngle = 45,
  gradientRepeat = 1,
  gradientSpeed = 0,
  noiseScale = 3,
  noiseContrast = 1,
  noiseBalance = 0.5,
  noiseSpeed = 0.15,
  warpAmount = 0.35,
  blendAmount = 0.5,
}: GeneratedShaderProps) {
  const shaderContext = useShaderContext();

  // Speed dials integrate on the CPU: each hook advances a phase uniform
  // (phase += speed x delta), so speed changes retime the pattern without
  // snapping or rebuilding — which is also why speed props stay out of the
  // effect deps below.
  const gradientSpeedPhase = useAnimatableSpeed(gradientSpeed);
  const gradientSpeedUniform = useAnimatableUniform(gradientSpeed);
  const noiseSpeedPhase = useAnimatableSpeed(noiseSpeed);

  useEffect(() => {
    if (!shaderContext) return;

    // Dials ride uniforms. This generated component rebuilds its material on
    // prop change (the deps below), which is generated-code shorthand — the
    // registry pattern pushes new values through stable uniforms instead.
    const gradientAngleUniform = uniform(gradientAngle);
    const gradientRepeatUniform = uniform(gradientRepeat);
    const noiseScaleUniform = uniform(noiseScale);
    const noiseContrastUniform = uniform(noiseContrast);
    const noiseBalanceUniform = uniform(noiseBalance);
    const warpAmountUniform = uniform(warpAmount);
    const blendAmountUniform = uniform(blendAmount);

    // Directional ramp: project the centered point onto the angle's direction.
    const gradientRadians = gradientAngleUniform.mul(Math.PI / 180);
    const gradientDirection = vec2(cos(gradientRadians), sin(gradientRadians));
    // Two animated forms behind GPU gates (the docs LinearGradient's trick):
    // a cosine ping-pong that fades in above speed 0, and a fract() sawtooth
    // conveyor that takes over above repeat 1 — both identities at their
    // resting values, so the static single-pass ramp is bit-for-bit intact.
    const gradientField = (p: TSLNode) => {
      const coord = dot(p.sub(0.5), gradientDirection).add(0.5);
      const cosineAnimated = sub(1, cos(coord.add(gradientSpeedPhase).mul(Math.PI))).mul(0.5);
      const animated = mix(
        clamp(coord, 0, 1),
        cosineAnimated,
        smoothstep(0, 0.01, gradientSpeedUniform),
      );
      const tiled = fract(coord.mul(gradientRepeatUniform).sub(gradientSpeedPhase));

      return mix(animated, tiled, smoothstep(1, 1.01, gradientRepeatUniform));
    };

    // 3D simplex with the animation phase on z: the pattern morphs in
    // place. Raw noise spans roughly -1..1; add/mul rescales to 0..1.
    const noiseRaw = (p: TSLNode) =>
      simplexNoise(vec3(p.mul(noiseScaleUniform), noiseSpeedPhase))
        .add(1)
        .mul(0.5);
    // Balance shifts the whole field darker or lighter (0.5 is identity);
    // contrast stretches it around the midpoint (1 is identity).
    const noiseField = (p: TSLNode) => {
      const balanced = clamp(noiseRaw(p).add(noiseBalanceUniform.sub(0.5).mul(2)), 0, 1);

      return clamp(balanced.sub(0.5).mul(noiseContrastUniform).add(0.5), 0, 1);
    };

    // Domain warp: two far-apart taps of the driver become the x/y of a
    // push vector; the source is then read at the pushed position.
    const warpField = (p: TSLNode) => {
      const pushX = noiseField(p).sub(0.5);
      const pushY = noiseField(displace(p, vec2(5.2, 1.3))).sub(0.5);

      return gradientField(displace(p, vec2(pushX, pushY).mul(warpAmountUniform)));
    };

    // Blend mode "mix": amount fades between the untouched base and
    // the blended value, like layer opacity.
    const blendField = (p: TSLNode) => {
      const a = warpField(p);
      const b = noiseField(p);

      return mix(a, b, blendAmountUniform);
    };

    // The door from pattern to color: the field picks a position along
    // the ramp, mixed in oklab.
    const rampStops = [
      { position: 0, color: vec3(...parseColorString('#1B2A6B')) },
      { position: 0.5, color: vec3(...parseColorString('#7C3AED')) },
      { position: 1, color: vec3(...parseColorString('#F472B6')) },
    ];
    const rampColor = colorRamp(blendField(uv()), rampStops, 'oklab');

    const material = new MeshBasicNodeMaterial();

    material.colorNode = rampColor;

    const mesh = new Mesh(new PlaneGeometry(2, 2), material);

    shaderContext.scene.add(mesh);
    shaderContext.scheduler.requestRender();

    return () => {
      shaderContext.scene.remove(mesh);
      try {
        material.dispose();
      } catch {
        // three/webgpu can throw during dispose under Strict Mode double-invoke
      }
      try {
        mesh.geometry.dispose();
      } catch {
        // same
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    shaderContext,
    gradientAngle,
    gradientRepeat,
    noiseScale,
    noiseContrast,
    noiseBalance,
    warpAmount,
    blendAmount,
  ]);

  return null;
}
