'use client';

// Generated by the Matter editor. A bare Matter component: mount it inside a
// ShaderScene. Fields are functions of the sample position — warping is
// calling a field at a shifted point — and every editor dial arrived below
// as a prop with the editor's value as its default.
import { useEffect } from 'react';

import { colorRamp, displace, simplexNoise } from '@lovo/matter';
import { useAnimatableSpeed, useShaderContext } from '@lovo/matter-react';
import { parseColorString } from '@lovo/matter/color';
import { clamp, cos, dot, mix, sin, uniform, uv, vec2, vec3 } from 'three/tsl';
import type { ShaderNodeObject } from 'three/tsl';
import { Mesh, MeshBasicNodeMaterial, PlaneGeometry } from 'three/webgpu';
import type { Node } from 'three/webgpu';

type TSLNode = ShaderNodeObject<Node>;

export interface GeneratedShaderProps {
  /** Gradient angle, 0 to 360. Defaults to 45. */
  gradientAngle?: number;
  /** Noise scale, 0.5 to 10. Defaults to 3. */
  noiseScale?: number;
  /** Noise speed, 0 to 1. Defaults to 0.15. */
  noiseSpeed?: number;
  /** Warp amount, 0 to 1. Defaults to 0.35. */
  warpAmount?: number;
  /** Blend amount, 0 to 1. Defaults to 0.5. */
  blendAmount?: number;
}

export function GeneratedShader({
  gradientAngle = 45,
  noiseScale = 3,
  noiseSpeed = 0.15,
  warpAmount = 0.35,
  blendAmount = 0.5,
}: GeneratedShaderProps) {
  const shaderContext = useShaderContext();

  // Speed dials integrate on the CPU: each hook advances a phase uniform
  // (phase += speed x delta), so speed changes retime the pattern without
  // snapping or rebuilding — which is also why speed props stay out of the
  // effect deps below.
  const noiseSpeedPhase = useAnimatableSpeed(noiseSpeed);

  useEffect(() => {
    if (!shaderContext) return;

    // Dials ride uniforms. This generated component rebuilds its material on
    // prop change (the deps below), which is generated-code shorthand — the
    // registry pattern pushes new values through stable uniforms instead.
    const gradientAngleUniform = uniform(gradientAngle);
    const noiseScaleUniform = uniform(noiseScale);
    const warpAmountUniform = uniform(warpAmount);
    const blendAmountUniform = uniform(blendAmount);

    // Directional ramp: project the centered point onto the angle's direction.
    const gradientRadians = gradientAngleUniform.mul(Math.PI / 180);
    const gradientDirection = vec2(cos(gradientRadians), sin(gradientRadians));
    const gradientField = (p: TSLNode) => clamp(dot(p.sub(0.5), gradientDirection).add(0.5), 0, 1);

    // 3D simplex with the animation phase on z: the pattern morphs in
    // place. Raw noise spans roughly -1..1; add/mul rescales to 0..1.
    const noiseField = (p: TSLNode) =>
      simplexNoise(vec3(p.mul(noiseScaleUniform), noiseSpeedPhase))
        .add(1)
        .mul(0.5);

    // Domain warp: two far-apart taps of the driver become the x/y of a
    // push vector; the source is then read at the pushed position.
    const warpField = (p: TSLNode) => {
      const pushX = noiseField(p).sub(0.5);
      const pushY = noiseField(displace(p, vec2(5.2, 1.3))).sub(0.5);

      return gradientField(displace(p, vec2(pushX, pushY).mul(warpAmountUniform)));
    };

    // Blend mode "mix": amount fades between the untouched base and
    // the blended value, like layer opacity.
    const blendField = (p: TSLNode) => {
      const a = warpField(p);
      const b = noiseField(p);

      return mix(a, b, blendAmountUniform);
    };

    // The door from pattern to color: the field picks a position along
    // the ramp, mixed in oklab.
    const rampStops = [
      { position: 0, color: vec3(...parseColorString('#1B2A6B')) },
      { position: 0.5, color: vec3(...parseColorString('#7C3AED')) },
      { position: 1, color: vec3(...parseColorString('#F472B6')) },
    ];
    const rampColor = colorRamp(blendField(uv()), rampStops, 'oklab');

    const material = new MeshBasicNodeMaterial();

    material.colorNode = rampColor;

    const mesh = new Mesh(new PlaneGeometry(2, 2), material);

    shaderContext.scene.add(mesh);
    shaderContext.scheduler.requestRender();

    return () => {
      shaderContext.scene.remove(mesh);
      try {
        material.dispose();
      } catch {
        // three/webgpu can throw during dispose under Strict Mode double-invoke
      }
      try {
        mesh.geometry.dispose();
      } catch {
        // same
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shaderContext, gradientAngle, noiseScale, warpAmount, blendAmount]);

  return null;
}
